//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoeniksDBEntity : DbContext
    {
        public FoeniksDBEntity()
            : base("name=FoeniksDBEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bog> Bog { get; set; }
        public virtual DbSet<Brætspil> Brætspil { get; set; }
        public virtual DbSet<Lokale> Lokale { get; set; }
        public virtual DbSet<Medlem> Medlem { get; set; }
        public virtual DbSet<Udlån> Udlån { get; set; }
        public virtual DbSet<Udstyr> Udstyr { get; set; }
    }
}
