//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medlem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medlem()
        {
            this.Udlån = new HashSet<Udlån>();
        }
    
        public int medlemid { get; set; }
        public string brugernavn { get; set; }
        public string fornavn { get; set; }
        public string efternavn { get; set; }
        public string adgangskode { get; set; }
        public string email { get; set; }
        public Nullable<int> rang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Udlån> Udlån { get; set; }
    }
}
