//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotteHullet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EJL52_DBEntities : DbContext
    {
        public EJL52_DBEntities()
            : base("name=EJL52_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bog> Bog { get; set; }
        public virtual DbSet<Brætspil> Brætspil { get; set; }
        public virtual DbSet<Lokale> Lokale { get; set; }
        public virtual DbSet<Medlem> Medlem { get; set; }
        public virtual DbSet<Udlån> Udlån { get; set; }
        public virtual DbSet<Udstyr> Udstyr { get; set; }
    }
}
