//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotteHullet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokale
    {
        public int lokaleid { get; set; }
        public string lokalenavn { get; set; }
        public string møbler { get; set; }
        public string lokation { get; set; }
        public Nullable<bool> udlånes { get; set; }
        public string kommentar { get; set; }
        public Nullable<bool> udlånt { get; set; }
    }
}
