//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotteHullet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medlem
    {
        public int medlemid { get; set; }
        public string brugernavn { get; set; }
        public string fornavn { get; set; }
        public string efternavn { get; set; }
        public string adgangskode { get; set; }
        public string email { get; set; }
        public Nullable<int> rang { get; set; }
    }
}
