//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotteHullet
{
    using System;
    using System.Collections.Generic;
    
    public partial class UdlånBog
    {
        public int udlånid { get; set; }
        public Nullable<System.DateTime> udlåningsdato { get; set; }
        public Nullable<System.DateTime> afleveringsdato { get; set; }
        public Nullable<System.DateTime> reeleafleveringsdato { get; set; }
        public Nullable<int> bogid { get; set; }
    
        public virtual Bog Bog { get; set; }
    }
}
